permalink: pretty

collections:
  info:
    output: true
    permalink: /:collection/:path/


defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: info
    values:
      layout: default
